### ISSUE TITLE
avoid use of StdVec in the python API

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/tsid#102]
Hi,

According to https://github.com/loco-3d/crocoddyl/issues/795#issuecomment-661998782, we can avoid teh use of `StdVec` in the python API. This would be much cleaner for the end user.

It is used eg. in 

https://github.com/stack-of-tasks/tsid/blob/567982b46ab06522bf414cad180d941a7cc532a8/exercizes/notebooks/TSID_ex1.ipynb#L330

**Comment by andreadelprete** [comment]
Good point. Just fixed with commit 7d240c3aedde96280b6db696b21c1302d86a81c1

**Comment by nim65s** [comment]
Thanks !
