### ISSUE TITLE
devel stalled

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/tsid#12]
Dear all,
The devel branch is stalled and behind master.
I suggest to remove the devel branch if this is fine with everyone.

**Comment by jcarpent** [comment]
I would suggest to keep the devel branch for developments and master for stable versions.
In other words, we can align both branches and make a minor release of the current version and push it on robotpkg.

**Comment by olivier-stasse** [comment]
Exactly and for this reason the _devel_ branch should be ahead of master not the other way around. For it means that _devel_ is not used for development and is currently meaningless.

**Comment by olivier-stasse** [comment]
Or you mean that devel was used to develop a specific topic. Thus I would recommend to rename it as a specific topic for book keeping and restart a new devel branch from master.

**Comment by jcarpent** [comment]
I just meant that devel should be used for development and keep master a bit static, similarly as we do for pinocchio or eigenpy for instance.

**Comment by olivier-stasse** [comment]
Dear Justin, Thanks for the clarification.
