### ISSUE TITLE
COM mask in Python

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/tsid#120]
We are looking for a way to only consider the vertical COM. I guess it should be with the setMask introduced in #116. I don't see it in Python. Is there an alternative way that I am missing?

Thx

**Comment by andreadelprete** [comment]
It seems the function has not been exposed in Python. I'm working on another issue right now, but I hope I can do that later today.

**Comment by andreadelprete** [comment]
It should be ok now. I've also cleaned up a bit by standardizing the names of the methods to get and set the mask.

**Comment by nmansard** [comment]
Thanks a lot!
