### ISSUE TITLE
Redefinition of m_mask in TaskJointPosture

### ISSUE THREAD

**Issue by jacqueszhong** [stack-of-tasks/tsid#123]
Hello, 
There is a small issue in TaskJointPosture.hpp (so I'm not sure this is worth a Pull request).
With the redefinition of m_mask in TaskJointPosture.hpp, getMask() does not work properly for me and prints the m_mask of the parent class TaskMotion (where m_mask is not initialized).

Best regards,

**Comment by andreadelprete** [comment]
Well spotted! It's weird that this is tolerated by the compiler. I'm gonna fix it right away

**Comment by andreadelprete** [comment]
Fix with my last commit to devel 3f35957f2f2567942b865c470acec04d836d7751
