### ISSUE TITLE
define locally the `BOOST_BIND_GLOBAL_PLACEHOLDERS` and undef it afterwards

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/tsid#128]
You can define locally the `BOOST_BIND_GLOBAL_PLACEHOLDERS` and undef it afterwards if needed.

_Originally posted by @jcarpent in https://github.com/stack-of-tasks/tsid/pull/126#discussion_r596082867_

**Comment by nim65s** [comment]
As this is needed in many places, some refactoring of the headers would help.

**Comment by jcarpent** [comment]
Having fwd.hpp included in all files would be helpful.
