### ISSUE TITLE
m_baseDynamics for InverseDynamicsFormulationAccForce

### ISSUE THREAD

**Issue by timothy233** [stack-of-tasks/tsid#136]
Hi,

I checked the code on `inverse-dynamics-formulation-acc-force.cpp`. It seems the `m_baseDynamics` only uses as constraint the dynamic of unactuated root joint (first 6 row). I am wondering why not use dynamics of full body?

**Comment by andreadelprete** [comment]
You can check the [wiki](https://github.com/stack-of-tasks/tsid/wiki), in particular the "problem formulation" section.

**Comment by timothy233** [comment]
Thanks. I checked the paper and understood it.
