### ISSUE TITLE
Test inconsistent

### ISSUE THREAD

**Issue by pdandignac** [stack-of-tasks/tsid#16]
At
https://github.com/stack-of-tasks/tsid/blob/master/src/formulations/inverse-dynamics-formulation-acc-force.cpp#L130
Either the test should be "if (weight<=0.0)", or the message should be  "weight should be negative".
I think that the test should be "if (weight<=0.0)" and the message is the right one.

The same type of inconsistency occurs at
https://github.com/stack-of-tasks/tsid/blob/master/src/formulations/inverse-dynamics-formulation-acc-force.cpp#L135
 https://github.com/stack-of-tasks/tsid/blob/master/src/formulations/inverse-dynamics-formulation-acc-force.cpp#L154
and https://github.com/stack-of-tasks/tsid/blob/master/src/formulations/inverse-dynamics-formulation-acc-force.cpp#L159

**Comment by andreadelprete** [comment]
I think you're right, but I let @olivier-stasse answer you because I think he has been the one writing those lines of code.

**Comment by andreadelprete** [comment]
fixed by ed35eef4b9ffb2cef4c75de86d5fc2b83e2fb2ab
