### ISSUE TITLE
Cannot surpress SolverHQuadProg output

### ISSUE THREAD

**Issue by sjauhri** [stack-of-tasks/tsid#185]
**Installation: tsid from conda-forge 1.6.0**

I am using the solver: 
tsid.SolverHQuadProgFast("qp solver")

When calling a 'solve' using this solver, a huge amount of information is printed on the terminal.

Is there any way to disable this?

**Comment by jcarpent** [comment]
Thanks @sjauhri for raising this issue. Could you try with the latest release 1.6.3?
Could you provide a tiny example to try on my side?

**Comment by sjauhri** [comment]
Hi @jcarpent 
Thanks for the quick response!
Yes, with version 1.6.3 the issue is resolved. Closing this issue now.

Just FYI, I was running: https://github.com/stack-of-tasks/tsid/blob/master/exercizes/ex_1_ur5.py

**Comment by jcarpent** [comment]
Super. Nice to get your feedback.
