### ISSUE TITLE
TaskJointPosVelAccBounds not exposed to the python API

### ISSUE THREAD

**Issue by sjauhri** [stack-of-tasks/tsid#187]
Installation: TSID version 1.6.3 from conda

Hello team,
I am running the example: https://github.com/stack-of-tasks/tsid/blob/master/exercizes/ex_1_ur5.py and am trying to add joint position bounds in the formulation.
However, it seems that the TaskJointPosVelAccBounds is not exposed to the python API....
Is there any other way to set the robot's joint position limits in the formulation?

**Comment by jcarpent** [comment]
Thanks for the report. @EtienneAr Would you have time to expose it?

**Comment by EtienneAr** [comment]
I will have a look :+1:

**Comment by jcarpent** [comment]
Solved via #189.
