### ISSUE TITLE
BSD License

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/tsid#20]
Dear all,
We will soon switch to BSD License v2.0 to ease our collaborations.
Let me know if there is a problem with this.
Cheers,
Olivier.

**Comment by nim65s** [comment]
@olivier-stasse as @andreadelprete pointed in #31, this project can only be GPL as long as it depends on eiquadprog

**Comment by olivier-stasse** [comment]
We could implement the same solution than for hpp: making it a plugin :(

**Comment by andreadelprete** [comment]
I am fine with the plugin option as long as it doesn't complexify the installation of TSID. So...does it?

**Comment by andreadelprete** [comment]
What's the status of this issue? Can we close it?

**Comment by olivier-stasse** [comment]
This PR #85
We still have to move eigen-quadprog towards the external library.
This is an ongoing work.
