### ISSUE TITLE
SE3 Inequality Task or Constraint

### ISSUE THREAD

**Issue by sjauhri** [stack-of-tasks/tsid#211]
Hello team,

I am using the tsid python API.
Is there a way to add an SE3 Inequality Task or SE3 Inequality Constraint in the Python API?
I want to constrain the motion of my end-effector to avoid collision

**Comment by andreadelprete** [comment]
Hi @sjauhri , the short answer is no. The longer answer is that this is related to this ongoing discussion:
https://github.com/stack-of-tasks/tsid/discussions/204

Actually the discussion has been silent for a while now, but the long term plan is to integrate some new tasks to achieve collision avoidance. I suggest you to read the above-mentioned discussion and contribute there if you wish.
