### ISSUE TITLE
github action on OSX conda Release failing on osqp solver

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/tsid#215]
Dear @fabinsch,
Currently unrelated PR #212 fails due to an error when testing the Oxford osqp solver on Linux /OS Conda Release.
See here for instance:
https://github.com/stack-of-tasks/tsid/actions/runs/6538220426/job/17753685229?pr=212

I suspect that this is related to an incompatibility or a release problem as the same test seems to work for Linux - ROS Noetic Debug , where as in PR #213 it was the reverse (i.e failing for Linux ROS Noetic Debug and fine for Linux/OS Conda Release).

As you authored the test, could you give an insight on how to fix the problem ?

**Comment by fabinsch** [comment]
Hi @olivier-stasse,

it is correct that I added proxqp and osqp. In this test, we create random problems and then check if the solver can solve the problem up to `EPS=1e-3`.  We are not setting any accuracy for the solvers, which leads to  `epsAbs = 1e-5` for [osqp](https://github.com/stack-of-tasks/tsid/blob/master/src/solvers/solver-osqp.cpp#L35). We could try to increase the accuracy we ask for by doing `solver.set_epsilon_absolute(1e-5)` for example. Also, we can fix the random seed to be sure to always run on the same problem.

If you want, I can open another PR where I do this change, and we can check if the tests pass. If yes, we can rebase the open PRs.

**Comment by olivier-stasse** [comment]
That will be awesome. Thank you very for your reactivity and your commitment.
