### ISSUE TITLE
Plans for Pinocchio3.x integration?

### ISSUE THREAD

**Issue by egordv** [stack-of-tasks/tsid#231]
Hello Andrea!
Pinocchio3 was recently released, promising new great features like RigidConstraint and other.
Do you have any plans to migrate current TSID implementation to Pinocchio3.x version?

**Comment by andreadelprete** [comment]
Good point. At the moment there's no plan as far as I know. Honestly, I don't even know what we could gain by switching to pinocchio 3. Maybe @jcarpent could give us some insights on this?

**Comment by nim65s** [comment]
CI already switched to pinocchio 3. If we want to stay on pinocchio 2, we'll propably have some work to do about it.

**Comment by andreadelprete** [comment]
I think it's fine to stay with Pinocchio 3 as far as I can see, so I'm gonna close this issue for now.
