### ISSUE TITLE
Compatibility Issue with Latest Pinocchio Version and TSID

### ISSUE THREAD

**Issue by lvjonok** [stack-of-tasks/tsid#235]
I was not sure whether the [initial issue](https://github.com/conda-forge/tsid-feedstock/issues/34) was in the right place, so I will duplicate it here too.

Right now the latest `tsid` version published in conda refers to the pinocchio version below 3.0.0. What are the procedures to bump and rebuild the library? Is it doable?

**Comment by jcarpent** [comment]
We were off the last few weeks. This is ongoing in conda.
