### ISSUE TITLE
support for 3D contacts models?

### ISSUE THREAD

**Issue by stonneau** [stack-of-tasks/tsid#30]
To handle quadruped robots such as HyQ in tsid, we had to modify the urdf files of the robot by adding virtual joints that allow to represent the 3D contacts of the robot as a 6D ones.

(urdf here: https://github.com/humanoid-path-planner/hpp-rbprm-robot-data/blame/master/data/hyq_description/urdf/hyq_contact6D.urdf)

While this might be useful to further constrain inclination of the leg when the robot is in contact,
this can be problematic in the general case.

Do you think we should extend tsid to handle 3D contacts or not ?

**Comment by andreadelprete** [comment]
There's already a [PR](https://github.com/stack-of-tasks/tsid/pull/22) addressing this issue, which I should merge soon (I was just waiting for the Memmo winter school to be over).

**Comment by stonneau** [comment]
Sorry for the noise then, shall I close the issue or wait for the merge to do it ? Thanks

**Comment by andreadelprete** [comment]
I've just merged the PR so I close this issue
