### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by xuhuairuogu** [stack-of-tasks/tsid#52]
Problem Description
   My OS is Ubuntu18.04.
   First, I installed PInocchio successfully following the instructions on this website https://stack-of-tasks.github.io/pinocchio/download.html :
  1. Add robotpkg apt repository
  2. Install Pinocchio
    sudo apt install robotpkg-py27-pinocchio
  3. Configure environment variables(add the following to the file ~/.bashrc and source it)
    export PATH=/opt/openrobots/bin:$PATH
    export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
    export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
    export PYTHONPATH=/opt/openrobots/lib/python2.7/site-packages:$PYTHONPATH
   Then, I started installing tsid following the instructions on this website and failed when executing cmake:  
![Screenshot from 2019-10-12 14-31-03](https://user-images.githubusercontent.com/10009476/66696272-0d910680-ecfd-11e9-89c7-82801ec6559a.png)
  I am really confused.

**Comment by olivier-stasse** [comment]
Dear @xuhuairuogu 
Several solutions are possible
1/ You want to continue with sources:
I would suggest to try:
```
export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig/:$PKG_CONFIG_PATH
```
Note that there is '/' just after pkgconfig
2/ You might try to use the binaries:
apt-get install robotpkg-tsid
apt-get install robotpkg-py27-tsid

Note that there is currently a problem with the python bindings, and I will push a PR to fix this problem this week-end.

**Comment by xuhuairuogu** [comment]
Thanks for your reply. Now I have successfully compiled and installed pinocchio, OpenSceneGraph3.4, PythonQt, gepetto-viewer, gepetto-viewer-corba and tsid all from source. However, when I execute examples related to Gepetto GUI, for example exercizes/ex_1.py, 3D models cannot be displayed. It seems that everything except for model displaying works well.
![Screenshot from 2019-10-14 17-24-42](https://user-images.githubusercontent.com/10009476/66741223-9481e280-eea7-11e9-91fd-636b6e17329f.png)
![Screenshot from 2019-10-14 17-25-27](https://user-images.githubusercontent.com/10009476/66741248-a499c200-eea7-11e9-85c0-7fa87a7c99b8.png)

**Comment by jcarpent** [comment]
Hi @xuhuairuogu,

It seems that you did not install the osg-dae pluging necessary to load your meshes (because they are collada files).
You can do that using the following command:
`sudo apt-get install robotpkg-osg-dae`
See https://github.com/stack-of-tasks/pinocchio/issues/705 for additional details.

Best,

Justin

**Comment by xuhuairuogu** [comment]
HI, on Ubuntu18.04, there is not robotpkg-osg-dae. Therefore, I install collada using the following command:
`sudo apt-get install libcollada-dom2.4-dp-dev`
and recompile OpenSceneGraph3.4 and osgdb_dea.so is generated.
However, when executing `python ex_1.py`, a new error appears:
![Screenshot from 2019-10-15 10-04-54](https://user-images.githubusercontent.com/10009476/66794238-4d413380-ef33-11e9-8be3-940e9615d1fa.png)

**Comment by xuhuairuogu** [comment]
I have converted all dae files to stl files by Blender and changed the 3D model file path in romeo.urdf. Although it is not an elegant way, it really works.
