### ISSUE TITLE
Exercises instructions

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/tsid#56]
A few glitches after the class on TSID:

- line https://github.com/stack-of-tasks/tsid/blob/761194b6447e0380a1af8cff325b47e162af2f38/exercizes/notebooks/Installation%20process.html#L13130 is not needed. robotpkg-py27-...-...-corba only depends on omniORB from the official repositories.
- for some obscure reasons, virtualenv removes `/usr/lib/python2.7/dist-packages` from `PYTHONPATH`.  You may want to add a warning in the instructions.

**Comment by andreadelprete** [comment]
Thanks @jmirabel, I've just fixed it!
