### ISSUE TITLE
Change gravity

### ISSUE THREAD

**Issue by sduminy** [stack-of-tasks/tsid#57]
Hey,
I would like to change the gravity in TSID, to turn it to 0. 
In Pinocchio, I would do that with model.gravity = pinocchio.Motion.Zero(). Yet I don't have a direct access to the pinocchio model in the TSID robot wrapper (robot.model() gives me access, I believe, to a copy of the pinocchio model). 

What do you think is the best way to change the gravity in TSID? Should I add a setter function in TSID, e.g. setGravity(const Motion & g), and wrap it in python?

Thanks for your advices.

**Comment by andreadelprete** [comment]
Since there was no update about this for 20 days I consider the issue solved.
