### ISSUE TITLE
Problem referencing Pinocchio

### ISSUE THREAD

**Issue by mklvcm** [stack-of-tasks/tsid#63]
Hi guys,

I'm trying to follow your installation instructions and I'm getting the following error:

![image](https://user-images.githubusercontent.com/54096564/72608581-171eb000-3977-11ea-8dd8-a1b2bf18bc45.png)

Any ideas what can be wrong?

Thanks,
Misha.

**Comment by andreadelprete** [comment]
Probably that method was deprecated and now it has been removed from pinocchio. Maybe you can try replacing it with:
```
q = se3.getNeutralConfiguration(robot.model(), srdf, False)
```
or
```
se3.loadReferenceConfigurations(robot.model(), srdf, False)
q = robot.model().referenceConfigurations["name_of_the_configuration"]
```
where you should replace ```name_of_the_configuration``` with the actual name of the configuration you want to use (which should be written in the srdf file).

**Comment by mklvcm** [comment]
Thank you Andrea.

Yes, the method seems deprecated. The method you suggested does not seem to be there neither.

I also tried to build **pinocchio** v2.10 from March last year. That version has the function. But when I run it it crashes with core dump :(

I'd like to give this library a try but I'm kind of stuck. Do you know of any versions that are proved working? Do you by any chance have a VM with all stuff installed? Or something?..

Thanks,
Misha.

**Comment by andreadelprete** [comment]
Hi Misha,

I' ve just pushed in the devel branch a fix to your problem. I've also converted all python files to python 3 (pinocchio has already switched, so it was about time TSID did it too). For playing with the library I suggest you to use the scripts in the folder exercises (rather than the ones in tests).

**Comment by mklvcm** [comment]
That is massively appreciated! I'll tell all my friends that Andrea is the man! Let me give it a try now .. :)
