### ISSUE TITLE
[Feature] Task force is not implemented 

### ISSUE THREAD

**Issue by thomasfla** [stack-of-tasks/tsid#67]
from https://github.com/stack-of-tasks/tsid/blob/761194b6447e0380a1af8cff325b47e162af2f38/src/tasks/task-contact-force.cpp#L1 It looks like the task force in not implemented yet.
@andreadelprete, any advise on how to implement it? Or a workaround to set a pure force task for a 3d contact?

**Comment by andreadelprete** [comment]
You can simply use the methods [setForceReference](https://github.com/stack-of-tasks/tsid/blob/761194b6447e0380a1af8cff325b47e162af2f38/include/tsid/contacts/contact-point.hpp#L100) and [setRegularizationTaskWeightVector](https://github.com/stack-of-tasks/tsid/blob/761194b6447e0380a1af8cff325b47e162af2f38/include/tsid/contacts/contact-point.hpp#L101) of `ContactPoint`.

**Comment by thomasfla** [comment]
Thank you very much @andreadelprete !
