### ISSUE TITLE
Test tsid-formulation

### ISSUE THREAD

**Issue by andreadelprete** [stack-of-tasks/tsid#68]
Dear @nim65s 
I see that in this commit 243e072862726858fa24a2506e0b6deb50a35bcf you have commented the unit test tsid-formulation. Is there a reason? Should we put it back in now?

**Comment by nim65s** [comment]
Hum, a commit "tmp" without more explanations should not have made it to master, sorry for that. 

Yes, I think I had to deactivate the test because it was not passing during a `make release`, but was passing otherwise.

**Comment by andreadelprete** [comment]
Hi @nim65s 
did you correct this commit? If so we can close this issue.

**Comment by nim65s** [comment]
Absolutely, these tests are passing now :)
