### ISSUE TITLE
Wrong convergence of the contact force reference

### ISSUE THREAD

**Issue by thomasfla** [stack-of-tasks/tsid#70]
@paleziart repported a wrong convergence of the contact forces when a reference is given.

The contact force equality task seems to be miss-formulated :
https://github.com/stack-of-tasks/tsid/blob/761194b6447e0380a1af8cff325b47e162af2f38/src/contacts/contact-point.cpp#L109

I think `m_forceRegTask.setVector(m_fRef);` should be replaced by `m_forceRegTask.setVector(m_fRef * m_weightForceRegTask);`

Same applies https://github.com/stack-of-tasks/tsid/blob/761194b6447e0380a1af8cff325b47e162af2f38/src/contacts/contact-6d.cpp#L141

**Comment by andreadelprete** [comment]
You're right, that's a mistake! Probably nobody noticed before because typically the reference force is zero. It should be
```
m_forceRegTask.setVector(A*m_fRef);
```
Could you fix that? Otherwise I can try to do it tomorrow.

**Comment by thomasfla** [comment]
`m_forceRegTask.setVector(m_fRef * m_weightForceRegTask);` right?
I'll PR the fix. Thanks !

**Comment by andreadelprete** [comment]
> `m_forceRegTask.setVector(m_fRef * m_weightForceRegTask);` right?

Not sure about this. I am sure it'd work using the matrix `A`, because it's a classic matrix-vector product, where `A` is a diagonal matrix, whose diagonal is `m_weightForceRegTask`.
If instead you multiply `m_weightForceRegTask * m_fRef` you're multiplying two vectors of the same size, and I'm afraid it's gonna compute their dot product.

**Comment by andreadelprete** [comment]
Hi @thomasfla 
any news on this issue? If it's solved, could you close it?

**Comment by thomasfla** [comment]
Thanks @paLeziart

**Comment by andreadelprete** [comment]
Thanks guys!
