### ISSUE TITLE
Use https://github.com/stack-of-tasks/eiquadprog

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/tsid#76]
Hi,

@gabrielebndn externalized eiquadprog code into another package, so we should use this one here.

Who wants to handle that ?

If no one is available, I can give a try.

Also, this dependency is LGPL-v3, so this would fix #20

**Comment by andreadelprete** [comment]
Unfortunately I'm not able to handle this right now, but I can review the pull request if someone does it.

**Comment by andreadelprete** [comment]
BTW, this was already discussed in #9
